### ISSUE TITLE
Remove Zesty support

### ISSUE THREAD

**Issue by buggtb** [juju-solutions/charm-mysql#25]
Remove the zesty support or fix the python issue, currently it doesn't install but I can't find the metadata.yaml thats in the store.

**Comment by marcoceppi** [comment]
We've pushed up a new release

**Comment by buggtb** [comment]
mysql-zesty2/0*  error        idle       4        35.174.172.186                     hook failed: "install"

Ya did?

**Comment by marcoceppi** [comment]
We removed zesty from the supported series. It's in candidate now.
