### ISSUE TITLE
Unable to deploy mysql

### ISSUE THREAD

**Issue by orion-belt** [juju-solutions/charm-mysql#32]
I am not able deploy mysql. I am getting problem to get a machine. What will be the possible reseaon for the same ?

user@user:~$ **juju status**
Model    Controller  Cloud/Region         Version  SLA          Timestamp
default  lxd-test    localhost/localhost  2.4.4    unsupported  18:22:13+02:00

App      Version  Status   Scale  Charm    Store       Rev  OS      Notes
mysql             waiting    0/1  mysql    jujucharms   58  ubuntu   

Unit        Workload  Agent       Machine  Public address  Ports  Message
mysql/5     waiting   allocating  7                               waiting for machine

Machine  State    DNS           Inst id        Series  AZ  Message
7        down                   pending        zesty       **no matching agent binaries available**

**Comment by token47** [comment]
I have a similar problem because it picks zesty by default, if I force --series xenial then it installs correctly. Since zesty is EOL shouldn't it be removed? Or at least not be picked by default?
